Adjustments and Binary Tree
Constantine-Rozoff/DataStruct pull request #1
Opened 2024-12-01 16:08 UTC by Constantine-Rozoff

2024-12-01 18:11 UTC, Delvin09 requested changes

2024-12-01 18:11 UTC, Delvin09 commented on DataStruct.sln.DotSettings.user
>  ﻿<wpf:ResourceDictionary xml:space="preserve" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml" xmlns:s="clr-namespace:System;assembly=mscorlib" xmlns:ss="urn:shemas-jetbrains-com:settings-stora
треба додати у гітІгнор

2024-12-01 18:11 UTC, Delvin09 commented on DataStructLib/BinaryTree.cs
> +        Add(_root, item);
else ?

2024-12-01 18:11 UTC, Delvin09 commented on DataStructLib/BinaryTree.cs
> +        if (node != null)
обхід зроблен, але додання до масиву немає)

2024-12-01 18:11 UTC, Delvin09 commented on DataStructLib/MyList.cs
> +            if (i < 0 || i > _innerArray.Length)
Не _innerArray.Length, а Count

2024-12-01 18:11 UTC, Delvin09 commented on DataStructLib/MyList.cs
> +            if (i < 0 || i > _innerArray.Length)
Не _innerArray.Length, а Count

2024-12-01 18:11 UTC, Delvin09 commented on DataStructLib/MyList.cs
> +            if (_innerArray[i].Equals(null))
навіщо? у листі може бути null'и

2024-12-01 18:11 UTC, Delvin09 commented on DataStructLib/MyList.cs
>          int newSize = _innerArray.Length * 2;
так тут повинна бути перевірка, або у тебе постіно сбілшиватися масив при доданні елемента

2024-12-01 18:11 UTC, Delvin09 commented on DataStructLib/MyList.cs
> +        return 0;
чому 0? якщо не знайшли елемент, то повертаємо -1, бо такого індекса немае
Якщо повертати 0 - то це буде як перший елемент

2024-12-02 08:02 UTC, Constantine-Rozoff commented on DataStructLib/MyList.cs
> +        return 0;
Тут я переграв сам себе) І твій попередній комент (return MyIndexOf(item) >= 0) вирішив ось так пофіксити. Виправлю.

2024-12-03 10:51 UTC, Delvin09 approved these changes

2024-12-03 10:51 UTC, Delvin09 commented on DataStructLib/MyList.cs
> +        if (Count >= _innerArray.Length)
ця провірка повинна бути у методі Increase. Щоб не дублювати її у всі місця виклику Increase

2024-12-03 10:51 UTC, Delvin09 commented on DataStructLib/BinaryTree.cs
> +                //Console.WriteLine(node.Value);
не залишай такого роду коментарі у коді

2024-12-03 12:59 UTC, Constantine-Rozoff commented on DataStructLib/BinaryTree.cs
> +                //Console.WriteLine(node.Value);
Я не свідомо) Щось дебажив та забув видалити

2024-12-03 13:00 UTC, merged