Interfaces calling for help
Constantine-Rozoff/DataStruct pull request #3
Opened 2024-12-05 17:10 UTC by Constantine-Rozoff

2024-12-05 17:13 UTC, Constantine-Rozoff commented on Tests/ListTests.cs
>          var index1 = myList.MyIndexOf(5);
Щось ніяк не можу роздуплитися з інтерфейсами(( Як мені передавати інтеджер як параметр в MyIndexOf при виклику, якщо він приймає IMyList інстанс?

2024-12-05 18:22 UTC, Delvin09 requested changes

2024-12-05 18:22 UTC, Delvin09 commented on DataStructInterfaces/IMyCollection.cs
> +public interface IMyCollection : IComparable
Не думаю що колекції повинні бути IComparable

2024-12-05 18:22 UTC, Delvin09 commented on DataStructInterfaces/IMyList.cs
> +    int Count { get; }
Count можна винести до IMyCollection

2024-12-05 18:22 UTC, Delvin09 commented on DataStructLib/MyList.cs
> +    public int MyIndexOf(IMyList item)
а чого так? требаж object? приймати

2024-12-05 18:22 UTC, Delvin09 commented on DataStructLib/MyList.cs
> +            if(_innerArray[i] != null && item.CompareTo(_innerArray[i]) == 0)
навіщо CompareTo? тут достатьньо Equals

2024-12-05 18:22 UTC, Delvin09 commented on DateStruct.Interfaces/DateStruct.Interfaces.csproj
> +    <PropertyGroup>
мені здається це зайвий прект

2024-12-05 18:22 UTC, Delvin09 commented on Tests/ListTests.cs
>          var index1 = myList.MyIndexOf(5);
написав вище, він не повинен приймати IMyList, метод Add повинен приймати object

2024-12-09 08:29 UTC, Delvin09 requested changes

2024-12-09 08:29 UTC, Delvin09 commented on DataStructInterfaces/IMyBinaryTree.cs
> +    public abstract class Node;
воу воу, а вот так не нужно
может просто создать интерфейс для для нода?

```
interface INode
{
  INode Left { get; set; }
  INode Right { get; set; }
  int Data { get; }
}
```

2024-12-09 08:29 UTC, Delvin09 commented on DataStructInterfaces/IMyLinkedList.cs
> +    public abstract class Node;
Такеж саме, створи окремий інтерфейс до Нодів листа.

2024-12-09 08:29 UTC, Delvin09 commented on DataStructInterfaces/IMyCollection.cs
> +    public int Count { get;  set; }
сеттер зайвий

2024-12-09 08:29 UTC, Delvin09 commented on DataStructLib/MyLinkedList.cs
> +    public int Count { get; set; }
сеттер приватний

2024-12-09 08:29 UTC, Delvin09 commented on DataStructLib/MyList.cs
> +    public int Count { get; set; }
private set

2024-12-09 20:53 UTC, Delvin09 approved these changes

2024-12-09 20:53 UTC, Delvin09 commented on DataStructInterfaces/IListNode.cs
> +    object Value { get; set; }
object?

2024-12-09 20:53 UTC, Delvin09 commented on DataStructInterfaces/IMyCollection.cs
> +    void Add(object item);
object? - во всіх містах

2024-12-11 15:57 UTC, merged