Add generics
Constantine-Rozoff/DataStruct pull request #4
Opened 2024-12-09 17:09 UTC by Constantine-Rozoff

2024-12-09 21:05 UTC, Delvin09 requested changes

2024-12-09 21:05 UTC, Delvin09 commented on DataStructLib/MyList.cs
> +    private T[] _innerArray = new T[10];
T?[]

2024-12-09 21:05 UTC, Delvin09 commented on DataStructInterfaces/ITreeNode.cs
>      int Value { get; init; }
T Value

2024-12-09 21:05 UTC, Delvin09 commented on DataStructInterfaces/IMyList.cs
> +    public T[] ToArray();
ToArray move into IMyCollection
remove `public`

2024-12-09 21:05 UTC, Delvin09 commented on DataStructInterfaces/IMyLinkedList.cs
> +    public T[] ToArray();
ToArray move into IMyCollection
remove `public`

2024-12-09 21:05 UTC, Delvin09 commented on DataStructInterfaces/IMyLinkedList.cs
>      public abstract class Node;
зайве

2024-12-09 21:05 UTC, Delvin09 commented on DataStructInterfaces/IMyCollection.cs
>      public int Count { get; }
remove `public`

2024-12-09 21:05 UTC, Delvin09 commented on DataStructInterfaces/IMyCollection.cs
>      public void Clear();
remove `public`

2024-12-09 21:05 UTC, Delvin09 commented on DataStructLib/BinaryTree.cs
>      public void Add(int item)
T item

2024-12-09 21:05 UTC, Delvin09 commented on DataStructInterfaces/IMyBinaryTree.cs
>  public interface IMyBinaryTree
actually, you can remove this interface, and use IMyCollection in the BinaryTree, with T as a IComparable

2024-12-10 13:15 UTC, Constantine-Rozoff commented on DataStructInterfaces/IMyLinkedList.cs
> +    public T[] ToArray();
Не виходить мувнути ToArray в IMyCollection. В бінарі трі інша реалізація, там повертається інтеджер з рекурсивного методу і не можно його прикастувати до Т. Тому я розбив реалізацію для бінарі трі окремо(в інтерфейсі для нього) і він не наслідує MyCollection, а для лістів окремо (в MyCollection)

2024-12-11 07:45 UTC, Delvin09 approved these changes

2024-12-11 07:45 UTC, Delvin09 commented on DataStructLib/MyLinkedList.cs
> +            if (current.Value!.Equals(value))
current.Value може бути null, тому слід додати ще перевірки

2024-12-11 15:57 UTC, merged