Add DoubleLinkedList
Constantine-Rozoff/DataStruct pull request #5
Opened 2024-12-12 12:26 UTC by Constantine-Rozoff

Не знайшов, де знаходиться лінка на імплементацію з стратеджи паттерном. Тому робив своїми силами. Довелося багато оверайдити, але наче все працює. Подивись будь-ласка

2024-12-12 18:45 UTC, Delvin09 requested changes

2024-12-12 18:45 UTC, Delvin09 commented on DataStructInterfaces/IDoubleListNode.cs
> +    //IDoubleListNode<T> CreateNode(T value);
не залишай таких коментів

2024-12-12 18:45 UTC, Delvin09 commented on DataStructInterfaces/IListNode.cs
> +    IListNode<T> CreateNode(T value);
типу сам нод створює себе?

2024-12-12 18:45 UTC, Delvin09 commented on DataStructLib/DoubleLinkedList.cs
> +    private IDoubleListNode<T>? root;
в базовому класі є ж перший та останній ноди, навіщо створювати ще і тут?

2024-12-12 18:45 UTC, Delvin09 commented on DataStructLib/DoubleLinkedList.cs
> +    public override T[] ToArray()
деякі методи не треба перегружати, тому що вони працюють однаково, як для одно- так і дво-звязного списку

2024-12-13 12:53 UTC, Constantine-Rozoff commented
Все переробив. Прибрав зайві інтерфейси і зробив, щоб методи перент класу перевикористовувались. Але є маленька проблемка: почав ранити тести і взагалі нічого не працює)) Підкажи пліз, в чому помилка. Не вдається це розрулити

2024-12-15 11:14 UTC, merged