Add observable list
Constantine-Rozoff/DataStruct pull request #7
Opened 2024-12-18 19:00 UTC by Constantine-Rozoff

2024-12-20 17:05 UTC, Delvin09 approved these changes

2024-12-20 17:05 UTC, Delvin09 commented on DataStructInterfaces/IMyList.cs
> +    void RemoveAt(int index, T item = default);
вважаю що це зайве. можно просто передати при видаленні елемента, його самого, якщо він був + індекс де він був ростошованний

2024-12-21 09:51 UTC, Constantine-Rozoff commented on DataStructInterfaces/IMyList.cs
> +    void RemoveAt(int index, T item = default);
Так и було до цього. Але тепер в метод додався інший метод, який триггерить подію, а для нього обов'язково треба передати цей item. Тому довелося передавати його окремим параметром

2024-12-21 09:55 UTC, Constantine-Rozoff commented on DataStructInterfaces/IMyNotifier.cs
> +namespace DataStructInterfaces;
Подивився я на свій паттерн Observable та зрозумів, що в мене все реалізовано без підписок, що насправді порушує паттерн. До лінкед ліста зробив все по-iншому. Подивись будь-ласка, чи ця реалізація правильніша і чи все з нею ок. Якщо так, то для інших структур вже буду використовувати її

2024-12-21 11:15 UTC, Delvin09 requested changes

2024-12-21 11:15 UTC, Delvin09 commented on DataStructInterfaces/IMyList.cs
> +    void RemoveAt(int index, T item = default);
у RemoveAt  _innerArray[i] - і є твій item

2024-12-21 11:15 UTC, Delvin09 commented on DataStructInterfaces/IMyNotifier.cs
> +namespace DataStructInterfaces;
як це без підписок? у тебе було все горазд.
У С# нам не треба реалізовувати паттерн через класи (точніше це дуже опціонально).
Якщо у тебе в типі є event то на нього вже можна підписатися/відписатися, за допомогою += та -=

2024-12-21 11:15 UTC, Delvin09 commented on DataStructInterfaces/IMyNotifier.cs
> +public interface IMyNotifier<T>
а що це за подія? що саме тут нотіфікується?

2024-12-21 11:15 UTC, Delvin09 commented on DataStructInterfaces/IMyNotifier.cs
> +    void Notify(ChangeType changeType, T? item = default, int? index = null);
мені здається що Notify повинен бути у interface IMyObserver<T>

2024-12-21 11:15 UTC, Delvin09 commented on DataStructInterfaces/ListObserver.cs
> +    public event EventHandler<ListChangedEventArgs<T>>? ListChanged;
а навіщо тут event якщо ти робишь через кастомну реалізацію паттерна?

2024-12-21 11:15 UTC, Delvin09 commented on DataStructInterfaces/ListObserver.cs
> +            ListChanged?.Invoke(this, new ListChangedEventArgs<T>(changeType, item, index));
саме тут повинна бути обробка події. Тобто кастомний код.

2024-12-21 11:15 UTC, Delvin09 commented on DataStructLib/MyLinkedList.cs
> +            Console.WriteLine($"Method: {changeType.ToString()}, Item: {item}, Index: {index.ToString()}");
краще зроби через Debug, щоб не засоряти консоль

2024-12-22 09:32 UTC, Constantine-Rozoff commented on DataStructInterfaces/IMyList.cs
> +    void RemoveAt(int index, T item = default);
Дійсно) Виправив

2024-12-22 10:46 UTC, Constantine-Rozoff commented on DataStructLib/MyLinkedList.cs
> +            Console.WriteLine($"Method: {changeType.ToString()}, Item: {item}, Index: {index.ToString()}");
Перевів роздрук до Дебагу, але в райдері не можу знайти де воно)) Треба, щоб ти показав на занятті, пліііііз!)

2024-12-22 14:22 UTC, Delvin09 approved these changes

2024-12-22 15:57 UTC, merged